require("leandrohsilveira.remap")
require("leandrohsilveira.set")
require("leandrohsilveira.lazy")
require("leandrohsilveira.colorscheme")
require("leandrohsilveira.filetypes")
require("leandrohsilveira.autocmds")
